#!/bin/bash
# Graphite uninstall script for Ubuntu 14.04 LTS
# Jason Dixon <jason@dixongroup.net>
# Modified by Chad Lung <chad.lung@gmail.com>

service carbon-cache stop
service graphite-api stop

# Remove various binaries, configuration files, and source directories
rm /etc/graphite-api.yaml
rm -r /opt/graphite
rm -r /usr/local/src/carbon
rm -r /usr/local/src/whisper
rm -r /usr/local/src/graphite-api
rm /usr/local/bin/*whisper*.py
rm /usr/local/lib/python2.7/dist-packages/whisper*
rm -r /srv/graphite
rm /etc/init/graphite-api.conf
rm /etc/init.d/carbon-cache

pip uninstall gunicorn

# Remove our system user for Carbon
userdel carbon
